jobs:
  include:

    - language: go
      go: "1.10"
      install:
        - make
      script:
        - make test

    - language: perl
      dist: trusty
      sudo: required
      services:
        - docker
      addons:
        apt:
          packages:
            - docker-ce
      install:
        - make -C perl-client -f docker.mk
      script:
        - make -C perl-client -f docker.mk test
